trigger:
- main
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

steps:
# Setup .NET
- task: UseDotNet@2
  displayName: 'Use .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'

# Setup Node.js for frontend
- task: NodeTool@0
  displayName: 'Use Node.js'
  inputs:
    versionSpec: '20.x'

# Install pnpm
- script: npm install -g pnpm
  displayName: 'Install pnpm'

# Install dependencies
- script: pnpm install --frozen-lockfile
  displayName: 'Install dependencies'

# Lint, build, test
- script: pnpm run lint
  displayName: 'Lint code'

- script: pnpm run build
  displayName: 'Build application'

- script: pnpm run test
  displayName: 'Run tests'

# Publish artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'

